data:
  raw:
    financial: data/raw/financialdata
    trades: data/raw/tradesdata
  processed:
    financial: data/processed/financial
    trades: data/processed/trades
    merged: data/processed/merged
    graph_data: data/forGNN
    quarter_graphs: data/forGNN/quarter_graphs
    
  labels:
    source_dir: data/processed/merged
    out_csv:    data/labels/labels.csv 
     
  features:
    wide_csv: data/forGNN/features_wide.csv
    feature_wide_edited: data/feature_wide/features_wide.csv

neo4j:
  uri:      ${NEO4J_URI}
  user:     ${NEO4J_USER}
  password: ${NEO4J_PASSWORD}    
